sudo: required

services: docker

language: python

python: 2.7

before_install:
- docker pull ubuntu:xenial

install:
- docker run -di --name test_env -v $(pwd):/home/travis/build/vincent-noel/python-libnuml ubuntu:xenial bash
- docker exec test_env /bin/bash /home/travis/build/vincent-noel/python-libnuml/scripts/install_dep.sh

script:
- docker exec test_env /bin/bash -c "cd /home/travis/build/vincent-noel/python-libnuml; /usr/bin/python setup.py install"
